stages:
    - build
    - upload

pages:
    stage: build
    image: ubuntu:18.04
    only:
        - master
    script:
        - apt-get update -y
        - apt-get install -y python3-venv make git curl doxygen
        - curl -LO https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz
        - tar xzf julia-*.tar.gz
        - rm -rf julia-*.tar.gz
        - mv julia-* /usr/local/julia
        - ln -s /usr/local/julia/bin/julia /usr/local/bin/julia
        - git submodule update --init
        - make
        - mv build public
    artifacts:
        paths:
        - public

upload-pages:
    stage: upload
    image: ubuntu:18.04
    only:
        - master@Scientific-IT-Systems/gr-documentation
    script:
        - apt-get update -y
        - apt-get install -y rsync sshpass
        - cd public
        - sshpass -p $RSYNC_PASSWORD rsync -av --delete --exclude downloads/ . rsync://$RSYNC_USERNAME@pgi-jcns.fz-juelich.de/gr-doc/
